name: Build and Deploy to Netlify
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # ( Build to ./dist or other directory... )
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            client:
              - 'client/**'
            server:
              - 'server/**'

      - name: deploy on netlify
        if: steps.changes.outputs.client == 'true'
        run: npm install


      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './client'
          production-deploy: true
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1